project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - research.qmd
    - teaching.qmd
    - books.qmd
  resources:
    - cv.pdf
    - CBOEQuotes.txt
    - Errata_KBack_2ed.pdf
    - utd.pdf
    - rice.pdf

    

    
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: Kerry Back
    file: index.qmd
    right:
       
      - text: "Research"
        file: research.qmd

      - text: "Teaching"
        file: teaching.qmd

      - text: "Books"
        file: books.qmd

      - text: "CV"
        file: cv.pdf

format:
  html:
    theme:
      light: flatly
      dark: superhero
    



